Statistical Modeling


Tasks:
Data Preparation: 
Handling Missing Data: Impute or remove missing values based on their nature and the quantity missing.
Feature Engineering: Create new features that might be relevant to TotalPremium and TotalClaims.
Encoding Categorical Data: Convert categorical data into a numeric format using one-hot encoding or label encoding to make it suitable for modeling.
Train-Test Split: Divide the data into a training set (for building the model) and a test set (for validating the model), typically using a 70:30 or 80:20 ratio.

In [41]:
import pandas  as pd
from analyzer import model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score

In [26]:
df=pd.read_csv(r'C:\Users\ASUS VIVO\Desktop\Week_3\Week_3\new_df.csv')

C:\Users\ASUS VIVO\AppData\Local\Temp\ipykernel_11912\1512857943.py:1: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r'C:\Users\ASUS VIVO\Desktop\Week_3\Week_3\new_df.csv')

In [31]:
df_sample=df.iloc[0:50000:2].copy() ## I took sample because the data is too large to fit on my memory 
df.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [32]:
df_encoded = pd.get_dummies(df_sample, drop_first=True)

In [33]:
x=df_encoded.drop('TotalPremium',axis=1)
y=df_encoded['TotalPremium']
x_trian,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [35]:
predicted_TotalPremium=model(x_trian,y_train,x_test)

In [36]:
predicted_TotalPremium

array([155.68326633,  78.84917835,  33.79223183, ...,  11.94459486,
         1.11688479, -14.09857957])